# Generated by Django 5.0.2 on 2024-03-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0002_remove_review_worker_review_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barapp.worker'),
        ),
    ]
