# Generated by Django 5.0.2 on 2024-03-16 22:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0003_alter_review_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rew_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='barapp.service'),
        ),
        migrations.AlterField(
            model_name='review',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barapp.worker'),
        ),
    ]
